# This is a basic workflow to help you get started with Actions

name: Create Cluster EKS

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
        default: "AWS_ECS_app"

      # AWS specifics
      aws_region:
        required: true
        type: string
      cluster_creation_role_arn:
        required: true
        type: string

      kubernetes_namespace:
        required: false
        type: string
        default: default

      use_load_balancer_controller:
        required: false
        type: boolean
        default: false
        description: Install load balancer controller required for using ALB in AWS. Without it, it will default to CLassic Load Balancer.

jobs:
  apply_kubernetes_resources: 
      name: Deploy nginx to EKS
      runs-on: ubuntu-latest
      
      permissions:
        id-token: write   # required for OIDC
        contents: read
  
      env:
        KUBE_NAMESPACE: ${{ inputs.kubernetes_namespace }}
        
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v6.0.0
          with:
            aws-region: ${{ inputs.aws_region }}
            role-to-assume: ${{ inputs.cluster_creation_role_arn }}
            role-session-name: Github-Kubernetes
  
        - name: Setup kubectl
          uses: azure/setup-kubectl@v4
          with:
            version: "latest"
  
        - name: Update kubeconfig for EKS
          run: |
            aws eks update-kubeconfig \
              --region eu-central-1 \
              --name task-eks

        - name: Install eksctl
          if: inputs.use_load_balancer_controller == true
          run: |
            ARCH=amd64
            PLATFORM=$(uname -s)_$ARCH
            curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
            
            # (Optional) Verify checksum
            curl -sL "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_checksums.txt" | grep $PLATFORM | sha256sum --check
            
            tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
            
            sudo install -m 0755 /tmp/eksctl /usr/local/bin && rm /tmp/eksctl

        # - name: Associate OICD with cluster # probably required if terraform apply was run from somewhere else
        #   run: |
        #     eksctl utils associate-iam-oidc-provider --region=eu-central-1 --cluster=task-eks --approve
        
        - name: Create Policies for Load Balancer Controller
          if: inputs.use_load_balancer_controller == true
          run: |
            # Download json with iam policy
            curl -O https://raw.githubusercontent.com/kubernetes-sigs/aws-load-balancer-controller/v2.14.1/docs/install/iam_policy.json
            # Create the policy
            if aws iam get-policy --policy-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/AWSLoadBalancerControllerIAMPolicy >/dev/null 2>&1; then
              echo "Policy exists, skipping"
            else
              aws iam create-policy --policy-name AWSLoadBalancerControllerIAMPolicy --policy-document file://iam_policy.json
            fi

            CLUSTER=task-eks
            NS=kube-system
            SA=aws-load-balancer-controller
            REGION="${{inputs.aws_region}}"
            
            # check if the serviceaccount exists in cluster
            if kubectl get sa -n "$NS" "$SA" >/dev/null 2>&1; then
              echo "ServiceAccount exists — deleting eksctl-managed SA and IAM role/IRSA binding"
              eksctl delete iamserviceaccount \
                --cluster="$CLUSTER" \
                --namespace="$NS" \
                --name="$SA" \
                --region="$REGION" || true
              # wait for removal
              kubectl wait --for=delete sa/"$SA" -n "$NS" --timeout=60s || true
            else
              echo "ServiceAccount not present"
            fi

            # create
            eksctl create iamserviceaccount \
              --cluster="$CLUSTER" \
              --namespace="$NS" \
              --name="$SA" \
              --attach-policy-arn="arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/AWSLoadBalancerControllerIAMPolicy" \
              --override-existing-serviceaccounts \
              --region="$REGION" \
              --approve
            
            # eksctl create iamserviceaccount \
            #   --cluster=task-eks \
            #   --namespace=kube-system \
            #   --name=aws-load-balancer-controller \
            #   --attach-policy-arn=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/AWSLoadBalancerControllerIAMPolicy \
            #   --override-existing-serviceaccounts \
            #   --region ${{inputs.aws_region}} \
            #   --approve

            # create EKS IAM service account if it doesn't exist
            # if kubectl get serviceaccount aws-load-balancer-controller -n kube-system >/dev/null 2>&1; then
            #   echo "service account exists, skipping eksctl"
            # else
            #   eksctl create iamserviceaccount \
            #     --cluster=task-eks \
            #     --namespace=kube-system \
            #     --name=aws-load-balancer-controller \
            #     --attach-policy-arn=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:policy/AWSLoadBalancerControllerIAMPolicy \
            #     --override-existing-serviceaccounts \
            #     --region ${{inputs.aws_region}} \
            #     --approve
            # fi
            
        - name: Install Helm
          if: inputs.use_load_balancer_controller == true
          run: |
            curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4
            chmod 700 get_helm.sh
            ./get_helm.sh

        - name: Install Load Balancer Controller
          if: inputs.use_load_balancer_controller == true
          run: |
            helm repo add eks https://aws.github.io/eks-charts
            helm repo update eks

            VPC_ID=$(aws ec2 describe-vpcs \
              --filters "Name=tag:Name,Values=eks-app-vpc" \
              --query "Vpcs[0].VpcId" --output text)

            echo "Debug: $VPC_ID"

            # Install CRD's manually - required when using helm upgrade instead of helm install
            # wget https://raw.githubusercontent.com/aws/eks-charts/master/stable/aws-load-balancer-controller/crds/crds.yaml
            # kubectl apply -f crds.yaml
            
            helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
              -n kube-system \
              --set clusterName=task-eks \
              --set serviceAccount.create=false \
              --set serviceAccount.name=aws-load-balancer-controller \
              --set vpcId=$VPC_ID \
              --set region=${{inputs.aws_region}} \
              --version 1.14.0 \
              --wait --rollback-on-failure
            # Verify if installed correctly
            kubectl get deployment -n kube-system aws-load-balancer-controller

        # - name: Get VPC ID from AWS
        #   if: inputs.use_load_balancer_controller == true
        #   id: vpc_get
        #   run: |

          

  
        - name: Deploy nginx (Deployment + LoadBalancer Service)
          working-directory: ${{ inputs.working_directory }}
          run: |
            # Deploy nginx
            if kubectl get namespace "$KUBE_NAMESPACE" >/dev/null 2>&1; then
              echo "Namespace $KUBE_NAMESPACE already exists"
            else
              kubectl create namespace $KUBE_NAMESPACE
            fi
            # kubectl run nginx --image=nginx:latest --port=80 --namespace=nginx-test
            # kubectl expose pod nginx --port=80 --type=LoadBalancer --name=nginx-service --namespace=nginx-test
            # kubectl apply -f eks-test-pod.yaml
  
        - name: Wait for LoadBalancer
          run: |
            echo "Waiting for AWS LoadBalancer provisioning..."
            for i in {1..18}; do
              HOSTNAME=$(kubectl get svc test-svc -n $KUBE_NAMESPACE -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo "")
              if [ -n "$HOSTNAME" ]; then
                echo "Deployment finished"
                echo "Service available at: http://$HOSTNAME"
                echo "## Nginx Service" >> $GITHUB_STEP_SUMMARY
                echo "http://$HOSTNAME" >> $GITHUB_STEP_SUMMARY
                break
              fi
              echo "Pending... (attempt $i/18)"
              sleep 10
            done
            if [ -z "$HOSTNAME" ]; then
              echo "LoadBalancer still pending after 3 minutes. Check AWS console."
              kubectl get svc test-svc -n $KUBE_NAMESPACE
            fi
