# This is a basic workflow to help you get started with Actions

name: Create Cluster EKS

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
        default: "AWS_ECS_app"

      # AWS specifics
      aws_region:
        required: true
        type: string
      cluster_creation_role_arn:
        required: true
        type: string

      kubernetes_namespace:
        required: false
        type: string
        default: default

jobs:
  apply_kubernetes_resources: 
      name: Deploy nginx to EKS
      runs-on: ubuntu-latest
      
      permissions:
        id-token: write   # required for OIDC
        contents: read
  
      env:
        KUBE_NAMESPACE: ${{ inputs.kubernetes_namespace }}
        
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v6.0.0
          with:
            aws-region: ${{ inputs.aws_region }}
            role-to-assume: ${{ inputs.cluster_creation_role_arn }}
            role-session-name: Github-Kubernetes
  
        - name: Setup kubectl
          uses: azure/setup-kubectl@v4
          with:
            version: "latest"
  
        - name: Update kubeconfig for EKS
          run: |
            aws eks update-kubeconfig \
              --region eu-central-1 \
              --name task-eks
        - name: Deploy nginx (Deployment + LoadBalancer Service)
          working-directory: ${{ inputs.working_directory }}
          run: |
            # Deploy nginx
            if kubectl get namespace "$KUBE_NAMESPACE" >/dev/null 2>&1; then
              echo "Namespace $KUBE_NAMESPACE already exists"
            else
              kubectl create namespace $KUBE_NAMESPACE
            fi
            # kubectl run nginx --image=nginx:latest --port=80 --namespace=nginx-test
            # kubectl expose pod nginx --port=80 --type=LoadBalancer --name=nginx-service --namespace=nginx-test
            kubectl apply -f eks-test-pod.yaml
  
        - name: Wait for LoadBalancer
          run: |
            echo "Waiting for AWS LoadBalancer provisioning..."
            for i in {1..18}; do
              HOSTNAME=$(kubectl get svc test-svc -n $KUBE_NAMESPACE -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo "")
              if [ -n "$HOSTNAME" ]; then
                echo "Deployment finished"
                echo "Service available at: http://$HOSTNAME"
                echo "## Nginx Service" >> $GITHUB_STEP_SUMMARY
                echo "http://$HOSTNAME" >> $GITHUB_STEP_SUMMARY
                break
              fi
              echo "Pending... (attempt $i/18)"
              sleep 10
            done
            if [ -z "$HOSTNAME" ]; then
              echo "LoadBalancer still pending after 3 minutes. Check AWS console."
              kubectl get svc test-svc -n $KUBE_NAMESPACE
            fi
